targets:
  $default:
    builders:
      view_model_generator:provider:
        enabled: true

builders:
  provider:
    import: "package:view_model_generator/view_model_generator.dart"
    builder_factories: ["viewModelProviderBuilder"]
    build_extensions: { ".dart": [".vm.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs:
      - ".freezed.dart"
      - ".g.dart"
      - ".dataforge.dart"
      - ".gr.dart"
      - ".chopper.dart"
